---
collections:
        - name: redhat.rhel_system_roles
          # version: 1.7.3
          source: https://cloud.redhat.com/api/automation-hub/
        - name: community.general
          # requires ansible 2.9+
        - name: ansible.posix
        - name: openstack.cloud
        # name: https://github.com/sap-linuxlab/community.sap_launchpad.git
        # type: git
        - name: https://github.com/sap-linuxlab/community.sap_install.git,dev
          type: git
