---
# tasks file for powervc_vm_create
#

- name: Retrieve list of all PowerVC images
  openstack.cloud.image_info:
    auth: "{{ os_add_auth | default(omit) }}"
  register: result

- name: Get latest image matching os_image_filter variable
  ansible.builtin.set_fact:
    os_image_name: "{{ result | to_json | from_json | json_query(query) | sort(reverse=True) | first }}"
  vars:
    query: "openstack_image[?starts_with(name, '{{ os_image_filter }}')].name"
  delegate_to: localhost

## TODO: Get Info from machine credential added
# check if ansible_ssh_private_key_file is defined, when machine credential is added
- name: Create an SSH key pair
  openstack.cloud.keypair:
    auth: "{{ os_add_auth | default(omit) }}"
    state: present
    name: ansible-ssh-key
    public_key_file: "{{ os_ssh_pub_key_file }}"
  delegate_to: localhost
  throttle: 1

- name: Create a network port
  openstack.cloud.port:
    state: present
    name: "{{ vm_create_name }}-port1"
    network: "{{ os_network }}"
    # fixed_ips:
    #  - ip_address: "{{ vm_create_ip }}"

- name: Create a new server instance
  openstack.cloud.server:
    state: present
    name: "{{ vm_create_name }}"
    image: "{{ os_image_name }}"
    flavor: "{{ vm_create_flavor_name }}"
    availability_zone: "{{ os_availability_zones[os_deploy_target] }}"
    key_name: ansible-ssh-key
    nics:
      - port-name: "{{ vm_create_name }}-port1"
    meta:
      hostname: "{{ vm_create_name }}"
      group: "{{ vm_group_name }}"
    timeout: 300
  register: vm

- name: Remove old ssh host keys from known hosts
  ansible.builtin.known_hosts:
    name: "{{  vm_create_name }}"
    state: absent
  when: tower_job_id is undefined
  throttle: 1
  failed_when: false
