---
########################################################
# Phase 1: server provisioning
#
# After running this playbook you will have
# servers with RHEL8 running on Google Cloud
#
# For input this playbook needs a dictionary with
# the following paramters

#   power_machines:
#           - name: server-name
#
#             group: label for group

# Additional variables which are used for PowerVC Environment
# to be defined in inventory


- hosts: localhost
  gather_facts: false

  tasks:
  - name: Output creation dictionary configuration
    debug:
      msg:
        - "Name: {{ item.name }}"
        - "boot: {{ item.bdisksize }}"
        - "disk2:{{ item.disk2size }}"
        - "type: {{ item.vmtype }}"
        - "group:{{ item.group }}"
    loop: "{{ power_machines }}"

  - name: Create GCE VMs
    include_role:
      name: power_vm_create
    vars:
      power_vm_name: "{{ item.name }}"
      power_vm_bdisksize: "{{ item.bdisksize }}"
      power_vm_disk2size: "{{ item.disk2size }}"
      power_vm_type: "{{ item.vmtype }}"
      power_vm_awx_group: "{{ item.group }}"
    loop: "{{ power_machines }}"
