---
- hosts: localhost
  gather_facts: false

  collections:
    - ansible.controller

  tasks:
    - name: Delete all hosts not needed in oneview_targets any more
      ansible.controller.host:
        name: "{{ item }}"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        state: absent
      ## syntax not correct, so just delete all and add them back again
      ## when item not in oneview_machines.name | tolist
      with_items: groups['oneview_targets']

    - name: Add OneView Host to inventory
      ansible.controller.host:
        name: "{{ item.name }}"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        enabled: "{{ item.enabled | default(true) }}"
        description: "{{ item.description | default(omit) }}"
        state: present
        variables:
          "{{ item | combine({ 'ansible_host': item.host_ip}) }}"
      loop: "{{ oneview_machines }}"
      when:
        - not remove | default ('false') | bool

    - name: initiate hana host group list
      set_fact:
        hanas: []

    - name: initiate s4hana host group list
      set_fact:
        s4hanas: []

    - name: create hana host group list
      set_fact:
        hanas: "{{ hanas + [ item.name ] }}"
      when: item.group == "hanas"
      loop: "{{ oneview_machines }}"

    - name: create s4hana host group list
      set_fact:
        s4hanas: "{{ s4hanas + [ item.name ]  }}"
      when: item.group == "s4hanas"
      loop: "{{ oneview_machines }}"

    - name: Add OneView Hosts to host groups
      ansible.controller.group:
        name: "{{ item }}"
        description: "{{ item }} hosts"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        state: present
        hosts:
          "{{ lookup('vars', item) }}"
        preserve_existing_hosts: true
        ## preserve_existing_children: true
      loop:
        - "s4hanas"
        - "hanas"
      when:
        - (item | length > 0)
        - not remove | default ('false') | bool

    - name: Add OneView Hosts to host group oneview_targets
      ansible.controller.group:
        name: "oneview_targets"
        description: "oneview target hosts"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        state: present
        hosts:
          "{{ s4hanas + hanas }}"
        preserve_existing_hosts: true
        ## preserve_existing_children: true
      when:
        - not remove | default ('false') | bool
