---
- hosts: oneview_targets
  gather_facts: no

  vars:

  tasks:
    - fail:
        msg: "You need to define ov_hardware for each host which should be deployed via this script"
      when: ov_hardware is undefined 
      delegate_to: localhost

    - name: Power Off compute in order to remove the profile
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
          name : '{{ ov_hardware }}'
          powerStateData:
            powerState: "Off"
            powerControl: "PressAndHold"
      register: oneview_server_info
      delegate_to: localhost

    - name: Remove the server profiles
      hpe.oneview.oneview_server_profile:
        hostname: "{{ oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ server_profile_name }}"
      delegate_to: localhost
      retries: 3
      delay: 3
      register: result
      until: not result.failed
      # sometimes the powerstate change seems still ongoing and serverprofile can not be removed
      # the retry ensures this will wokr anyway.
     
    ### FIXME: This might fail when same ov_template is used for different servers
    ### first deletion works, second will not have sth. to delete
    - name: Delete the Server Profile Template
      hpe.oneview.oneview_server_profile_template:
        hostname: "{{ oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ ov_template }}"
        params:
          force: True
      delegate_to: localhost

