---
- hosts: localhost
  gather_facts: false

  collections:
    - ansible.controller

  tasks:

    - name: Add OneView Host to inventory
      ansible.controller.host:
        name: "{{ item.name }}"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        enabled: "{{ item.enabled | default(true) }}"
        description: "{{ item.description | default(omit) }}"
        state: present
        variables:
          "{{ item }}"
      loop: "{{ oneview_machines }}"

    - name: initiate hana host group list
      set_fact:
        hanas: []

    - name: initiate s4hana host group list
      set_fact:
        s4hanas: []

    - name: create hana host group list
      set_fact:
        hanas: "{{ hanas + [ item.name ] }}"
      when: item.group == "hanas"
      loop: "{{ oneview_machines }}"

    - name: create s4hana host group list
      set_fact:
        s4hanas: "{{ s4hanas + [ item.name ]  }}"
      when: item.group == "s4hanas"
      loop: "{{ oneview_machines }}"

    - name: Add OneView Hosts to host groups
      ansible.controller.group:
        name: "{{ item }}"
        description: "{{ item }} hosts"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        state: present
        hosts:
          "{{ lookup('vars', item) }}"
      loop:
        - "s4hanas"
        - "hanas"

    - name: Add OneView Hosts to host group oneview_targets
      ansible.controller.group:
        name: "oneview_targets"
        description: "oneview target hosts"
        inventory: "{{ inventory_name_ov_hosts }}"
        validate_certs: false
        state: present
        hosts:
          "{{ lookup('vars', item) }}"
      loop:
        - "s4hanas"
        - "hanas"
