---
- hosts: localhost
  gather_facts: no

  vars:

  tasks:
    - fail:
        msg: "You need to define ov_hardware for each host which should be deployed via this script"
      when: item.ov_hardware is undefined 
      loop: "{{ oneview_machines }}"


    ### ov_profile is not used throughout this playbook => maybe this task is not needed
##    - name: Set Oneview Server Profile Name for the host in question
#      set_fact:
#        {"{{ item }}.ov_profile: RedHat_Ansible_demo_{{ item.name }}"}
#      when: item.ov_profile is undefined or item.ov_profile is not match ("^RedHat_Ansible_demo.*")
#      loop: "{{ oneview_machines }}"

    #- name: Gather facts about all Server Hardwares
      #oneview_server_hardware_facts:
        #hostname: "{{ item.oneview_host }}"
        #username: "{{ oneview_username }}"
        #password: "{{ oneview_password }}"
        #auth_login_domain: "{{ oneview_domain }}"
        #api_version: "{{ oneview_apiversion }}"
      #delegate_to: localhost
      #run_once: true

    - name: Power Off compute in order to remove the profile
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ item.oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
          name : '{{ item.ov_hardware }}'
          powerStateData:
            powerState: "Off"
            powerControl: "PressAndHold"
      loop: "{{ oneview_machines }}"

    - name: Remove the server profiles
      hpe.oneview.oneview_server_profile:
        hostname: "{{ item.oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ item.ov_template }}_{{ item.inventory_hostname_short }}"
      loop: "{{ oneview_machines }}"
    
    ### FIXME: This might fail when same ov_template is used for different servers
    ### first deletion works, second will not have sth. to delete
    - name: Delete the Server Profile Template
      hpe.oneview.oneview_server_profile_template:
        hostname: "{{ item.oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ item.ov_template }}"
        params:
          force: True
      loop: "{{ oneview_machines }}"

