---
- hosts: oneview_targets
  gather_facts: no

  tasks:
    - name: Create a server profile template
      hpe.oneview.oneview_server_profile_template:
        hostname: "{{ oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"

        state: present
        data:
          "{{ lookup('ansible.builtin.template', 'server_profile_template.j2') | from_yaml }}"
        params:
          force: true
      delegate_to: localhost
      register: result


    - debug: msg= "{{ result.msg }}"

    - name: Gather facts about the Server Profile Template by name
      hpe.oneview.oneview_server_profile_template_facts:
        hostname: "{{ oneview_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"

        name: "{{ server_profile_template_name }}"
      delegate_to: localhost

    - debug: var=server_profile_templates
