- hosts: oneview_targets
  
  # If we choose different iso file names we could deploy multiple nodes at the same time
  # we would still need serial: 1 as we wokr on the same filesystem to manipulate the iso-image.
  serial: 1
  gather_facts: no
  become: true

  tasks:

    - name: User role for creating a custom iso file
      include_role:
        name: custom-iso-role
      delegate_to: bastion_host
