---
- hosts: oneview_targets
  gather_facts: no
  become: false

  tasks:
  - name: debug hostvars
    debug:
     var: hostvars

  - name: debug bastion_host ipaddress
    debug:
     var: hostvars.bastion_host.ansible_host

  - name: debug http server ip and location
    debug:
     var: bastion_get_url

  - name: debug iso file server ip and location
    debug:
     var: rhel_installiso

  - name: Task to boot a system using an ISO from an HP iLO interface
    hpilo_boot:
      host: "{{ ilo_ip }}" 
      login: "{{ ilo_username }}"
      password: "{{ ilo_password }}"
      media: cdrom
      image: "{{ rhel_installiso }}" 
    delegate_to: localhost
