---
# call playbook with # ansible-playbook example_in_one_file.yml
- name: "Phase 03-C and 03-D -Setup HANA System Replication"
  hosts: hanas
  become: true

#  vars:
#    sap_domain: example.com
#
#    sap_hana_sid: 'DB1'
#    sap_hana_instance_number: '00'
#    sap_hana_install_master_password: 'my_hana_password'
#    # It is recommended to use vault instead of plain text passwords. Example please check README
#
#    ### Cluster Definition
#    sap_ha_install_pacemaker_cluster_name: cluster1
#    sap_hana_hacluster_password: 'my_hacluster'
#
#    sap_hana_cluster_nodes:
#      - node_name: hana1
#        node_ip: 10.0.0.101
#        node_role: primary
#        hana_site: DC01
#
#      - node_name: hana2
#        node_ip: 10.0.0.102
#        node_role: secondary
#        hana_site: DC02
#
#    sap_ha_set_hana_vip1: 10.0.0.200
#
#    sap_pacemaker_stonith_devices:
#      - name: "fence_name_for_rhevm"
#        agent: "fence_rhevm"
#        parameters: "disable_http_filter=1 ipaddr=rhev-manager.example.com login='rhevuser@internal' password=rhevuser-pw pcmk_host_map='hana1:hana1;hana2:hana2' power_wait=3 ssl=1 ssl_insecure=1"

# Access the IP Address of a particular hostname:
# hostvars[inventory_hostname].ansible_host
#

  roles:
    - community.sap_install.sap_ha_install_hana_hsr
    - community.sap_install.sap_ha_prepare_pacemaker
    - community.sap_install.sap_ha_install_pacemaker
    - community.sap_install.sap_ha_set_hana
