---
# Phase 3 - step A
#
# This playbook configures all systems in the
# HANA Group for consumption of SAP HANA software

- name: Phase 3-A - Prepare system for SAP HANA Installation
  hosts: hanas
  become: true

  pre_tasks:
     - name: Ensure VMware localhost entry is removed from /etc/hosts
       lineinfile:
           path: /etc/hosts
           state: absent
           regexp: '127.0.1.1\t{{ ansible_hostname }}.*'

     - name: re-read ansible_distribution_version as version might have changed
       ansible.builtin.setup:
           filter: ansible_distribution_version

     - name: show ansible_distribution_version
       debug:
          msg: "ansible_distribution_version: {{ ansible_distribution_version }}"
        
  roles:
     - community.sap_install.sap_general_preconfigure
     - community.sap_install.sap_hana_preconfigure
