---
# defaults file for powervc_vm_create
#
# Credentials for Openstack need  to be configured in AAP/AWX Controller
#
# Variables used , which are defined externally
#
# os_add_auth: additional parameters which are not defined in OpenStack Credential
# os_availability_zones: created from host list
# os_image_filter: Image to deploy from -> can also be moved to local var
# os_network: Netwrok to deploy to
#
# name of host to be created -> will be the dns hostname, too
vm_create_name:

# default vm flavor
vm_create_flavor: xlarge

# Group name
vm_group_name:

# Deploy target (defined in availabilty zone)
vm_create_deploy_target:
