---
- hosts: localhost
  gather_facts: true

  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:

    - name: Check if Config file is defined
      debug:
        msg: "{{ config_file }}"

    - name: Check if file exists
      stat:
        path: "{{ config_file }}"
      register: st

    - name: print content of OS_CLIENT_CONFIG_FILE
      ansible.builtin.debug:
        msg: "{{lookup('ansible.builtin.file', config_file) }}"
      when: st.stat.exists and st.stat.isreg

    - name: Include Variables from OpenStack credential file
      include_vars: "{{ config_file }}"
      when: st.stat.exists and st.stat.isreg

    - name: Output variables from OpenStack credential file
      debug:
        var: clouds
