---
- hosts: localhost
  gather_facts: true

  tasks:

    - name: Debug environment
      debug:
        var: ansible_env

    - name: Retrieve list of all PowerVC images
      openstack.cloud.image_info:
      register: power_images

    - debug:
        var: power_images
