---
- hosts: localhost
  gather_facts: true

  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:

    - name: Check if Config file is defined
      debug:
        msg: "{{ config_file }}"

    - name: Check if file exists
      stat:
        path: "{{ config_file }}"
      register: st

    - name: Include Variables from OpenStack credential file
      include_vars: "{{ config_file }}"
      when: st.stat.exists and st.stat.isreg

    - name: Debug Variables
      debug:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}

    - name: Retrieve list of all PowerVC images
      openstack.cloud.image_info:
        auth:
          auth_url: "{{ clouds.devstack.auth.auth_url }}"
          username: "{{ clouds.devstack.auth.username }}"
          password: "{{ clouds.devstack.auth.password }}"
          project_name: "{{ clouds.devstack.auth.project_name }}"
          project_domain_name: "{{ clouds.devstack.auth.project_domain_name | default(omit) }}"
          user_domain_name: "{{ clouds.devstack.auth.domain_name | default(omit) }}"
        validate_certs: "{{ clouds.devstack.verify }}"

      register: power_images

    - debug:
        var: power_images
