---
- hosts: localhost
  gather_facts: true

  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:

    - name: Check if Config file is defined
      debug:
        msg: "{{ config_file }}"

    - name: Check if file exists
      stat:
        path: "{{ config_file }}"
      register: st

    - name: add user_domain_name
      lineinfile:
        path: "{{ config_file }}"
        line: "      user_domain_name: Default"
        regexp: "^      user_domain_name:"
        insertafter: "^    auth:"

    - name: Debug content of file
      ansible.builtin.debug:
        msg: "the configfile content is {{lookup('ansible.builtin.file', config_file) }}"

    - name: Include Variables from OpenStack credential file
      include_vars: "{{ config_file }}"
      when: st.stat.exists and st.stat.isreg

    - name: Retrieve list of all PowerVC images
      openstack.cloud.image_info:
        auth: "{{ clouds.devstack.auth }}"
        validate_certs: "{{ clouds.devstack.verify }}"
      register: power_images

    - debug:
        var: power_images
